"""Add analysis_data relationship

Revision ID: 33eb8790d758
Revises: 664e2a87e386
Create Date: 2025-06-03 07:53:18.659463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33eb8790d758'
down_revision = '664e2a87e386'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
