"""Initial migration

Revision ID: 664e2a87e386
Revises: 
Create Date: 2025-06-03 07:49:41.530655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '664e2a87e386'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_sessions', 'analysis_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'correspondence'::character varying"))
    op.drop_index('idx_analysis_sessions_type', table_name='analysis_sessions')
    op.drop_index('idx_analysis_sessions_user_type', table_name='analysis_sessions')
    op.drop_index('idx_coordinates_data_session_type', table_name='coordinates_data')
    op.create_unique_constraint('uq_coordinates_session_type_name', 'coordinates_data', ['session_id', 'point_type', 'point_name'])
    op.drop_index('idx_eigenvalue_data_session_dim', table_name='eigenvalue_data')
    op.create_unique_constraint('uq_eigenvalue_session_dimension', 'eigenvalue_data', ['session_id', 'dimension_number'])
    op.alter_column('visualization_data', 'image_data',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('idx_visualization_data_session_type', table_name='visualization_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_visualization_data_session_type', 'visualization_data', ['session_id', 'image_type'], unique=False)
    op.alter_column('visualization_data', 'image_data',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_constraint('uq_eigenvalue_session_dimension', 'eigenvalue_data', type_='unique')
    op.create_index('idx_eigenvalue_data_session_dim', 'eigenvalue_data', ['session_id', 'dimension_number'], unique=False)
    op.drop_constraint('uq_coordinates_session_type_name', 'coordinates_data', type_='unique')
    op.create_index('idx_coordinates_data_session_type', 'coordinates_data', ['session_id', 'point_type'], unique=False)
    op.create_index('idx_analysis_sessions_user_type', 'analysis_sessions', ['user_id', 'analysis_type'], unique=False)
    op.create_index('idx_analysis_sessions_type', 'analysis_sessions', ['analysis_type'], unique=False)
    op.alter_column('analysis_sessions', 'analysis_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'correspondence'::character varying"))
    # ### end Alembic commands ###
